### ISSUE TITLE
hodmin fails with  undefined method `casecmp' error

### ISSUE THREAD

**Issue by luebbe** [rttools/hodmin#6]
Hodmin on a raspberry pi 2 fails regularly (75% of the time) with the following error:
```
pi@raspberrypi:~ $ hodmin list
/var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:146:in `online?': undefined method `casecmp' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:155:in `online_status'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:118:in `initialize'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:234:in `new'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:234:in `block in get_homies'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:232:in `each'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:232:in `get_homies'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:244:in `fetch_homie_dev_list'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_list.rb:12:in `hodmin_list'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/bin/hodmin:144:in `<top (required)>'
        from /usr/local/bin/hodmin:23:in `load'
        from /usr/local/bin/hodmin:23:in `<main>'
```
Is there anything I can do to solve this problem?

**Comment by rttools** [comment]
Please check all topics in your MQTT-tree: Hodmin selects all lines that are below your base_topic (defined in your hodmin-config-file) AND include the string '/$homie' to get a list of all Homie-devices. Do you have lines that do not belong to a Homie-device but include this string? Or is one of this devices missing the 'online'-topic? In this case hodmin would try to extract information about this device and fails. 
rttools

**Comment by luebbe** [comment]
Thanks for your reply. I checked the MQTT topics, but couldn't find anything that fits your description. Device Ids are identical and $homie and $online are both set.

```
pi@raspberrypi:~ $ mosquitto_sub -v -t homie/+/\$homie
homie/5ccf7f3bc462/$homie 2.0.0
homie/5ccf7ff99f99/$homie 2.0.0
homie/5ccf7ff99ea9/$homie 2.0.0
homie/18fe34f12ad6/$homie 2.0.0
homie/a020a611f230/$homie 2.0.0
homie/a020a611758b/$homie 2.0.0
homie/a020a6117237/$homie 2.0.0
^C
pi@raspberrypi:~ $ mosquitto_sub -v -t homie/+/\$online
homie/5ccf7f3bc462/$online false
homie/5ccf7ff99f99/$online true
homie/5ccf7ff99ea9/$online false
homie/18fe34f12ad6/$online true
homie/a020a611f230/$online true
homie/a020a611758b/$online true
homie/a020a6117237/$online false
^C
```

The next "hodmin list" worked, but the results don't look sane:

```
pi@raspberrypi:~ $ hodmin list
┌────────────┬──────┬─────────────┬─────────┬───────────────┬──────────┬──────────┐
│    mac     │online│   localip   │  name   │checksumfw_name│fw_version│upgradable│
├────────────┼──────┼─────────────┼─────────┼───────────────┼──────────┼──────────┤
│5ccf7f3bc462│false │192.168.0.208│ Sonoff  │               │          │   true   │
│5ccf7ff99f99│ true │192.168.0.161│ Sonoff  │               │          │  false   │
│5ccf7ff99ea9│false │192.168.0.56 │ Sonoff  │               │          │   true   │
│18fe34f12ad6│ true │192.168.0.106│Dachstuhl│               │          │  false   │
│            │      │             │         │               │  1.0.0   │          │
│            │      │             │         │               │  1.0.2   │          │
│            │      │             │         │               │  1.0.1   │          │
└────────────┴──────┴─────────────┴─────────┴───────────────┴──────────┴──────────┘
```

The next "hodmin list" crashed again:

```
pi@raspberrypi:~ $ hodmin list
/var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:146:in `online?': undefined method `casecmp' for nil:NilClass (NoMethodError)
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:155:in `online_status'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:118:in `initialize'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:234:in `new'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:234:in `block in get_homies'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:232:in `each'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:232:in `get_homies'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_tools.rb:244:in `fetch_homie_dev_list'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/lib/hodmin/hodmin_list.rb:12:in `hodmin_list'
        from /var/lib/gems/2.1.0/gems/hodmin-0.1.5/bin/hodmin:144:in `<top (required)>'
        from /usr/local/bin/hodmin:23:in `load'
        from /usr/local/bin/hodmin:23:in `<main>'

```
here are the $fw topics of the seven devices:
```
pi@raspberrypi:~ $ mosquitto_sub -v -t homie/+/\$fw/#
homie/5ccf7f3bc462/$fw/name sonoff
homie/5ccf7f3bc462/$fw/version 1.0.0
homie/5ccf7f3bc462/$fw/checksum bcca32a7f8715fd4c9971ddd494a25bb
homie/5ccf7ff99f99/$fw/name sonoff
homie/5ccf7ff99f99/$fw/version 1.0.2
homie/5ccf7ff99f99/$fw/checksum feb171cec923451f113c2c522973036e
homie/5ccf7ff99ea9/$fw/name sonoff
homie/5ccf7ff99ea9/$fw/version 1.0.0
homie/5ccf7ff99ea9/$fw/checksum a7274a735d404057f5496e4be381221d
homie/18fe34f12ad6/$fw/name dht-22
homie/18fe34f12ad6/$fw/version 1.0.1
homie/18fe34f12ad6/$fw/checksum 58c509a9f01af3011ed72bc9f77525d4
homie/a020a611f230/$fw/name yunshan-relay-contact-dht
homie/a020a611f230/$fw/version 1.0.1
homie/a020a611f230/$fw/checksum 159815b9f18b02c7f1ea17922255e793
homie/a020a611758b/$fw/name display
homie/a020a611758b/$fw/version 1.0.0
homie/a020a611758b/$fw/checksum 6e7280bc2f738680f20ac9a983513bee
homie/a020a6117237/$fw/name digimatic-connect
homie/a020a6117237/$fw/version 1.0.0
homie/a020a6117237/$fw/checksum 8606888e8292632ca40efd8351a5988e

```
what can I do next to resolve this issue?

**Comment by rttools** [comment]
Please check your config-file: Maybe, you're missing a blank in 'output'-section:
output:
  list: "HD.mac HD.online HD.localip HD.name FW.checksum FW.fw_name FW.fw_version"

Between FW.checksum FW.fw_name should be a blank.

Please test again after this and report.

**Comment by luebbe** [comment]
Thanks, will check when I'm back home. Is it possible that hodmin has a problem with dashes in firmware names? Things start to look bad after the fourth device which is called "dht-22". Just an idea.

**Comment by luebbe** [comment]
Hi, the config file was OK. It seems to work after I have increased the timeout value from 0.3 to 0.7.
My Raspberry needs a few (6-7) seconds to display the data for eight devices

**Comment by rttools** [comment]
Hi, thanks for your research. In hodmins next release I will put an additional text in README: The timeout depends on the number of clients and performance of hodmin-host-system.
Regarding your config: The listing above shows a colums 'checksumfw_name' which does not exist. Thats why this column is empty. 
I close this issue now as it seems to be OK.
